{
  "formatVersion": "1.1",
  "component": {
    "group": "me.moonboygamer",
    "module": "Buffered",
    "version": "1.0.0+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Buffered-1.0.0+1.20.4.jar",
          "url": "Buffered-1.0.0+1.20.4.jar",
          "size": 61122,
          "sha512": "411748e114bf8b822f33c02481a769f8e371988b1c63c5a79e00ab9788f8184b0250da5b5b8c866238b216b9a0a50cd296299f8b94833e059f8a2282a0668996",
          "sha256": "dadf83fca005d4d5b105bd708bc43f871e76a93019b86c73b5294562f69a95de",
          "sha1": "7234f263f89721a19273b1cfc0fac81e2b64d020",
          "md5": "f18928967d17ec3cccf43a7f8bc3b115"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.quiltmc",
          "module": "quilt-loader",
          "version": {
            "requires": "0.25.0"
          },
          "excludes": [
            {
              "group": "org.quiltmc",
              "module": "quilt-loader-dependencies"
            }
          ]
        },
        {
          "group": "org.quiltmc.quilted-fabric-api",
          "module": "quilted-fabric-api",
          "version": {
            "requires": "9.0.0-alpha.8+0.97.0-1.20.4"
          },
          "excludes": [
            {
              "group": "org.quiltmc",
              "module": "quilt-loader-dependencies"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "Buffered-1.0.0+1.20.4.jar",
          "url": "Buffered-1.0.0+1.20.4.jar",
          "size": 61122,
          "sha512": "411748e114bf8b822f33c02481a769f8e371988b1c63c5a79e00ab9788f8184b0250da5b5b8c866238b216b9a0a50cd296299f8b94833e059f8a2282a0668996",
          "sha256": "dadf83fca005d4d5b105bd708bc43f871e76a93019b86c73b5294562f69a95de",
          "sha1": "7234f263f89721a19273b1cfc0fac81e2b64d020",
          "md5": "f18928967d17ec3cccf43a7f8bc3b115"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Buffered-1.0.0+1.20.4-sources.jar",
          "url": "Buffered-1.0.0+1.20.4-sources.jar",
          "size": 37718,
          "sha512": "ebd5e098969f9960701d7a22b0a9c11bd490cd1dbc37ae1b48296b7d141bcbf217ca5994916dc7784e94a30cac4441e788ccb65df7000344b2637eff534e75d7",
          "sha256": "5c0144046bdc74576005974c806bbe6193ca3c06df6d272880dc5d974994cb7c",
          "sha1": "895093c19629fef493ca89b0b1a8d72a64964fa1",
          "md5": "ce4698db07226d4eaee1bd4d2d2c65be"
        }
      ]
    }
  ]
}
